# Generated by Django 2.2.6 on 2019-10-23 13:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("COAXOrderFlow", "COAXOrderFlow"),
                            ("CancelOrderFlow", "CancelOrderFlow"),
                            ("ColumbineBaseFlow", "ColumbineBaseFlow"),
                            ("FBSAOrderFlow", "FBSAOrderFlow"),
                            ("GetEventStatusFlow", "GetEventStatusFlow"),
                            ("GetEventsClient", "GetEventsClient"),
                            ("GetEventsFlow", "GetEventsFlow"),
                            ("ShowNetInfoAddressFlow", "ShowNetInfoAddressFlow"),
                            ("ShowNetInfoFlow", "ShowNetInfoFlow"),
                            ("ShowNetInfoVNASFlow", "ShowNetInfoVNASFlow"),
                            ("VULAOrderFlow", "VULAOrderFlow"),
                            ("datetime", "datetime"),
                        ],
                        help_text="The Type of this Flow (must be a class from columbine.flows)",
                        max_length=100,
                    ),
                ),
                (
                    "kwargs",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, help_text="The data for this Flow (as JSON)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The reason we created this Flow, as a text string"
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        help_text="The module.class.method() where we created this Flow"
                    ),
                ),
                (
                    "references",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, help_text="References for this Flow", null=True
                    ),
                ),
                (
                    "columbine_session_id",
                    models.CharField(
                        blank=True,
                        help_text="The Columbine generated session ID",
                        max_length=50,
                    ),
                ),
                (
                    "finished",
                    models.BooleanField(
                        default=False,
                        help_text="True if this Flow is considered finished (by our end). A finished flow will not be touched again by the workers.",
                    ),
                ),
                (
                    "result",
                    models.NullBooleanField(
                        help_text="True if all Transactions for this Flow have been make and their responses processed successfully in our end, False if an error happened during reply handling, None as long as we haven't fully processed the Flow yet."
                    ),
                ),
                (
                    "error",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="Any errormessage for this flow",
                        null=True,
                    ),
                ),
                (
                    "parent_flow",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent Flow of this Flow",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_flows",
                        to="columbine.Flow",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "references",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="Any external reference data for this Order",
                        null=True,
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "product_id",
                    models.TextField(
                        help_text="The Columbine product-id for the product."
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="The Columbine product name for this product",
                        null=True,
                    ),
                ),
                (
                    "descr",
                    models.TextField(
                        blank=True,
                        help_text="The Columbine product description (often missing)",
                        null=True,
                    ),
                ),
                (
                    "sik_value",
                    models.TextField(
                        help_text="The Columbine sik value for the product"
                    ),
                ),
                (
                    "product_parameter_type_list",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="The XML describing any parameters for this product (as JSON)",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "product_group_id",
                    models.TextField(
                        help_text="The Columbine id for this productgroup"
                    ),
                ),
                (
                    "product_group_name",
                    models.TextField(
                        help_text="The Columbine name for this productgroup"
                    ),
                ),
                (
                    "sik_value",
                    models.TextField(
                        help_text="The Columbine sik value for the productgroup"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="The products included in this productgroup",
                        to="columbine.Product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("validate", "validate"),
                            ("order", "order"),
                            ("ack", "ack"),
                        ],
                        help_text="The stage of this transaction - validate, order or ack?",
                        max_length=8,
                    ),
                ),
                (
                    "request_json",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The request data for this Transaction (as JSON)"
                    ),
                ),
                (
                    "request_xml_valid",
                    models.NullBooleanField(
                        help_text="True if the request XML is valid according to command.xsd, False if invalid, None if no validation has been attempted."
                    ),
                ),
                (
                    "reply_json",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="The reply data for this Flow (as JSON)",
                        null=True,
                    ),
                ),
                (
                    "reply_xml_valid",
                    models.NullBooleanField(
                        help_text="True if the reply XML is valid according to reply.xsd, False if invalid, None if no validation has been attempted."
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="The number of times the request worker has attempted to process this transaction",
                    ),
                ),
                (
                    "result",
                    models.NullBooleanField(
                        default=None,
                        help_text="True if this transaction has been processed successfully by the columbine_flow_processor, False if an error happened while processing this Transaction, None if it hasn't been processed yet.",
                    ),
                ),
                (
                    "error",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="Any error message from the <reply><error> element",
                        null=True,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="The Flow to which this Transaction belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="columbine.Flow",
                    ),
                ),
            ],
            options={"unique_together": {("flow", "stage")}},
        ),
        migrations.CreateModel(
            name="VNAS",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "references",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="Any external reference data for this VNAS, copied from the ShowNetInfoVNASFlow it came from",
                        null=True,
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The data for this VNAS"
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="The ShowNetInfoVNASFlow from which this VNAS came",
                        limit_choices_to={
                            "finished": True,
                            "name": "ShowNetInfoVNASFlow",
                            "result": True,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vnass",
                        to="columbine.Flow",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The Transaction which created or last updated this Circuit",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="columbine.Transaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "request_headers",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The HTTP request headers"
                    ),
                ),
                (
                    "request_body",
                    models.TextField(help_text="The HTTP request POST body"),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="The HTTP status code returned by the Columbine API",
                    ),
                ),
                (
                    "response_headers",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The HTTP response headers"
                    ),
                ),
                ("response_body", models.TextField(help_text="The HTTP response body")),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="The Transaction this HTTP request was triggered by",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="columbine.Transaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="RelationRuleType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this RelationRuleType",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "descr",
                    models.TextField(
                        help_text="Columbines description of this RelationRuleType"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The Columbine VNAS transaction which this rulerelation type was first seen in",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationruletypes",
                        to="columbine.Transaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="RelationRule",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "rule_group_1_products",
                    models.ManyToManyField(
                        help_text="The products in rule group 1 for this rule",
                        related_name="rule_group_1_rules",
                        to="columbine.Product",
                    ),
                ),
                (
                    "rule_group_2_products",
                    models.ManyToManyField(
                        help_text="The products in rule group 2 for this rule",
                        related_name="rule_group_2_rules",
                        to="columbine.Product",
                    ),
                ),
                (
                    "ruletype",
                    models.ForeignKey(
                        help_text="The type of this RelationRule",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationrules",
                        to="columbine.RelationRuleType",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The Columbine VNAS transaction to which this rulerelation belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationrules",
                        to="columbine.Transaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.CreateModel(
            name="ProductGroupCountRule",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "min_value",
                    models.IntegerField(
                        help_text="The minimum number of times this productgroup can be ordered"
                    ),
                ),
                (
                    "max_value",
                    models.IntegerField(
                        help_text="The maximum number of times this productgroup can be ordered"
                    ),
                ),
                (
                    "productgroup",
                    models.ForeignKey(
                        help_text="The Columbine Productgroup which this productgroup count rule comes from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productgroup_count_rules",
                        to="columbine.ProductGroup",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.AddField(
            model_name="productgroup",
            name="transaction",
            field=models.ForeignKey(
                help_text="The Columbine VNAS transaction which this productgroup comes from",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productgroups",
                to="columbine.Transaction",
            ),
        ),
        migrations.CreateModel(
            name="ProductCountRule",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "min_value",
                    models.IntegerField(
                        help_text="The minimum number of times this product can be ordered"
                    ),
                ),
                (
                    "max_value",
                    models.IntegerField(
                        help_text="The maximum number of times this product can be ordered"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The Columbine Product which this product count rule comes from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_count_rules",
                        to="columbine.Product",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.AddField(
            model_name="product",
            name="transaction",
            field=models.ForeignKey(
                help_text="The Columbine VNAS transaction which this product comes from",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="columbine.Transaction",
            ),
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=1,
                        help_text="How many of this product do we want in the Order",
                    ),
                ),
                (
                    "product_parameter_type_list",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        help_text="The product parameters (if any), as JSON",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The Columbine Order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderlines",
                        to="columbine.Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The Columbine Product",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderlines",
                        to="columbine.Product",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                help_text="The Products included in this Order",
                through="columbine.OrderLine",
                to="columbine.Product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vnas",
            field=models.ForeignKey(
                help_text="The Columbine VNAS this Order is based on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="columbine.VNAS",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time this object was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The date and time this object was last modified",
                    ),
                ),
                (
                    "jsonbody",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The body of this event (as JSON)"
                    ),
                ),
                ("name", models.CharField(help_text="Event name", max_length=255)),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The Transaction this event was received in",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="columbine.Transaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"], "abstract": False},
        ),
        migrations.AlterUniqueTogether(
            name="productgroup",
            unique_together={
                ("transaction", "product_group_id", "product_group_name", "sik_value")
            },
        ),
        migrations.AlterUniqueTogether(
            name="product", unique_together={("transaction", "product_id", "sik_value")}
        ),
    ]
