# Generated by Django 2.2.6 on 2019-10-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("columbine", "0002_auto_20191024_1127")]

    operations = [migrations.RemoveField(model_name="vnas", name="transaction")]
