# Generated by Django 2.2.6 on 2019-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("columbine", "0003_remove_vnas_transaction")]

    operations = [
        migrations.AddField(
            model_name="relationrule",
            name="rule_group_3_products",
            field=models.ManyToManyField(
                help_text="The products in rule group 3 for this rule (if any)",
                related_name="rule_group_3_rules",
                to="columbine.Product",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="name",
            field=models.CharField(
                choices=[
                    ("COAXOrderFlow", "COAXOrderFlow"),
                    ("CancelOrderFlow", "CancelOrderFlow"),
                    ("ColumbineBaseFlow", "ColumbineBaseFlow"),
                    ("FBSAOrderFlow", "FBSAOrderFlow"),
                    ("GetEventStatusFlow", "GetEventStatusFlow"),
                    ("GetEventsFlow", "GetEventsFlow"),
                    ("ShowNetInfoAddressFlow", "ShowNetInfoAddressFlow"),
                    ("ShowNetInfoFlow", "ShowNetInfoFlow"),
                    ("ShowNetInfoVNASFlow", "ShowNetInfoVNASFlow"),
                    ("VULAOrderFlow", "VULAOrderFlow"),
                ],
                help_text="The Type of this Flow (must be a class from columbine.flows)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="relationrule",
            name="rule_group_2_products",
            field=models.ManyToManyField(
                help_text="The products in rule group 2 for this rule (if any)",
                related_name="rule_group_2_rules",
                to="columbine.Product",
            ),
        ),
    ]
