# Generated by Django 2.2.6 on 2019-11-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("columbine", "0004_auto_20191025_1426")]

    operations = [
        migrations.RemoveField(model_name="relationrule", name="transaction"),
        migrations.RemoveField(model_name="relationruletype", name="transaction"),
        migrations.AddField(
            model_name="order",
            name="available_products",
            field=models.ManyToManyField(
                help_text="The Products available to this Order", to="columbine.Product"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow created to handle this Order.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow in which this Product was first seen.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="productcountrule",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow in which this ProductCountRule was first seen.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productcountrules",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow in which this ProductGroup was first seen.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productgroups",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="productgroupcountrule",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow in which this RelationRuleType was first seen.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productgroupcountrules",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="relationrule",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow to which this RelationRule belongs.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relationrules",
                to="columbine.Flow",
            ),
        ),
        migrations.AddField(
            model_name="relationruletype",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                help_text="The OrderFlow in which this RelationRuleType was first seen.",
                limit_choices_to={"name__endswith": "OrderFlow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relationruletypes",
                to="columbine.Flow",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="name",
            field=models.CharField(
                choices=[
                    ("COAXOrderFlow", "COAXOrderFlow"),
                    ("ColumbineBaseFlow", "ColumbineBaseFlow"),
                    ("FBSAOrderFlow", "FBSAOrderFlow"),
                    ("GetEventStatusFlow", "GetEventStatusFlow"),
                    ("GetEventsFlow", "GetEventsFlow"),
                    ("OrderCancelFlow", "OrderCancelFlow"),
                    ("ShowNetInfoAddressFlow", "ShowNetInfoAddressFlow"),
                    ("ShowNetInfoFlow", "ShowNetInfoFlow"),
                    ("ShowNetInfoVNASFlow", "ShowNetInfoVNASFlow"),
                    ("VULAOrderFlow", "VULAOrderFlow"),
                ],
                help_text="The Type of this Flow (must be a class from columbine.flows)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                help_text="The Products included in this Order",
                related_name="orders",
                through="columbine.OrderLine",
                to="columbine.Product",
            ),
        ),
        migrations.AlterField(
            model_name="productcountrule",
            name="product",
            field=models.ForeignKey(
                help_text="The Columbine Product which this product count rule relates to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_count_rules",
                to="columbine.Product",
            ),
        ),
        migrations.AlterField(
            model_name="productgroupcountrule",
            name="productgroup",
            field=models.ForeignKey(
                help_text="The Columbine Productgroup which this productgroup count rule comes from",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productgroupcountrules",
                to="columbine.ProductGroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product", unique_together={("product_id", "sik_value")}
        ),
        migrations.AlterUniqueTogether(
            name="productgroup",
            unique_together={("product_group_id", "product_group_name", "sik_value")},
        ),
        migrations.RemoveField(model_name="product", name="transaction"),
        migrations.RemoveField(model_name="productgroup", name="transaction"),
    ]
